name: editorconfig-checker

on:
  pull_request:
  push:

jobs:
  build:
    name: editorconfig-checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
